export type {
    PrepareServiceRecordLinkRequest,
    PrepareServiceRecordLinkResponse,
    SendServiceRecordLinkRequest,
    SendServiceRecordLinkResponse,
    ServiceRecordAssignment,
    ServiceRecordCase,
    ServiceRecordHeader,
    ServiceRecordLink,
    ServiceRecordLinkStatus,
    ServiceRecordOverview,
    ServiceRecordSession,
    ServiceRecordToken,
    ServiceRecordTokenState,
    SignatureDocStatus,
} from "@babyjamjam/shared/types/service-record";
