import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./query-provider";
import { Header } from "./(components)/root/Header";
import { MuiThemeProvider as ThemeProvider } from "./(components)/mui-theme-provider";
import { LanguageSwitcher } from "./(components)/nav-bar/LanguageSwitcher";
import { getLanguageForServerComp } from "./lib/i18n/getLanguageForServerComp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language = await getLanguageForServerComp();
  
  return (
    <html lang={language}>  
      <body className={`antialiased`}>
        <ThemeProvider>          
          <QueryProvider>
            <Header language={language} />
            {children}
            <LanguageSwitcher />
          </QueryProvider>
        </ThemeProvider>          
      </body>
    </html>
  );
}
