import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./query-provider";
import { NavBar } from "./(components)/nav-bar/NavBar";
import { MuiThemeProvider as ThemeProvider } from "./(components)/mui-theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body className={`antialiased`}>
        <ThemeProvider>          
          <QueryProvider>
            <NavBar />
            {children}
          </QueryProvider>
        </ThemeProvider>          
      </body>
    </html>
  );
}
