// allowed mime types for upload
export const allowed_mime_types = [
    'image/png',
    'image/jpeg',
    'image/jpg',
    'application/pdf',
] as const;

export type allowedmimetype = typeof allowed_mime_types[number];

// maximum file size (25mb in bytes)
export const max_file_size = 25 * 1024 * 1024;

// predefined document categories
export const predefined_categories = [
    'contract',
    'invoice',
    'receipt',
    'report',
    'certificate',
    'form',
    'notice',
    'employee-contract',
] as const;

export type documentcategory = typeof predefined_categories[number];

interface DocumentProps {
    id?: string; // CUID generated by DB, optional on create
    name: string;
    description?: string;
    category: string;
    tags: string[];
    mimetype: string;
    filesize: number;
    storagepath: string;
    storageurl?: string;
    orgid?: string;
    uploadedby: string;
    createdat: Date;
    updatedat: Date;
}

export class DocumentEntity {
    private readonly props: DocumentProps;

    constructor(props: DocumentProps) {
        this.props = {
            ...props,
        };
        this.assertInvariants();
    }

    /**
     * Invariants = rules that must always be true for this entity to be valid.
     * Enforce them once here so the rest of your code can trust the entity.
     */
    private assertInvariants(): void {
        if (!this.props.name) throw new Error("DocumentEntity: name is required");
        if (!this.props.category) throw new Error("DocumentEntity: category is required");
        if (!Array.isArray(this.props.tags)) throw new Error("DocumentEntity: tags must be an array");
        if (!this.props.mimetype) throw new Error("DocumentEntity: mimetype is required");
        if (typeof this.props.filesize !== "number" || this.props.filesize < 0) {
            throw new Error("DocumentEntity: filesize must be a non-negative number");
        }
        if (!this.props.storagepath) throw new Error("DocumentEntity: storagepath is required");
        if (!this.props.uploadedby) throw new Error("DocumentEntity: uploadedby is required");

        if (!(this.props.createdat instanceof Date) || Number.isNaN(this.props.createdat.getTime())) {
            throw new Error("DocumentEntity: createdat must be a valid Date");
        }
        if (!(this.props.updatedat instanceof Date) || Number.isNaN(this.props.updatedat.getTime())) {
            throw new Error("DocumentEntity: updatedat must be a valid Date");
        }
        if (this.props.updatedat < this.props.createdat) {
            throw new Error("DocumentEntity: updatedat cannot be before createdat");
        }
    }

    // Accessors (optional, but keeps props encapsulated)
    get id(): string | undefined { return this.props.id; }
    get name(): string { return this.props.name; }
    get description(): string | undefined { return this.props.description; }
    get category(): string { return this.props.category; }
    get tags(): string[] { return this.props.tags; }
    get mimetype(): string { return this.props.mimetype; }
    get filesize(): number { return this.props.filesize; }
    get storagepath(): string { return this.props.storagepath; }
    get storageurl(): string | undefined { return this.props.storageurl; }
    get orgid(): string | undefined { return this.props.orgid; }
    get uploadedby(): string { return this.props.uploadedby; }
    get createdat(): Date { return this.props.createdat; }
    get updatedat(): Date { return this.props.updatedat; }

    /**
     * Use this for "API JSON → select fields → create entity".
     * If you don't have updatedat yet, it defaults to createdat.
     * id is auto-generated by DB, so it's omitted here.
     */
    static create(
        props: Omit<DocumentProps, "id" | "updatedat"> & Partial<Pick<DocumentProps, "updatedat">>,
    ): DocumentEntity {
        return new DocumentEntity({
            ...props,
            updatedat: props.updatedat ?? props.createdat,
        });
    }

    /**
     * Reconstitute an entity from persistence data (used by Mapper).
     * This method is infrastructure-agnostic - it only knows domain types.
     */
    static reconstitute(props: DocumentProps): DocumentEntity {
        return new DocumentEntity(props);
    }

    static validatefilesize(size: number): boolean {
        return size > 0 && size <= max_file_size;
    }

    static validatemimetype(mimetype: string): boolean {
        return allowed_mime_types.includes(mimetype as allowedmimetype);
    }

    static validatecategory(category: string): boolean {
        return predefined_categories.includes(category as documentcategory);
    }
}
