interface EformsignDocProps {
    id?: number; // auto-generated by DB, optional on create
    documentId: string;
    createdDate: Date;
    updatedDate: Date;
    // doc status code example: 060 = pending, 050 = completed, 070 = collecting daily records, 080 = rejected
    statusType: string;
    // doc status detail example: "대기", "완료", "일일기록 수집 중", "거부"
    statusDetail: string;
    // step type example: "05" = participant, "06" = reviewer
    stepType: string;
    // step index example: "2"
    stepIndex: string;
    // step name example: "이용자 성명"
    stepName: string;
    // step recipients example: [{ type: "05", name: "이용자 성명", sms: "010-1234-5678" }]
    stepRecipientType: string;
    // step recipient name example: ["이용자 성명"]
    stepRecipientName: string;
    // step recipient sms example: ["010-1234-5678"]
    stepRecipientSms: string;
    // expired date example: 2025-12-13
    expiredDate: Date;
    // expired example: true
    expired: boolean;
    // FK to client
    clientId: number;
    // Two-phase (서비스제공기록지) collection window — null for non-record docs
    collectionStartDate?: Date | null;
    collectionEndDate?: Date | null;
    collectionPeriodDays?: number | null;
    // Phase 2 finalization metadata
    finalizedAt?: Date | null;
    forceFinalize?: boolean;
}

export class EformsignDocEntity {
    private readonly props: EformsignDocProps;

    constructor(props: EformsignDocProps) {
        this.props = {
            ...props,
        };
        this.assertInvariants();
    }

    /**
     * Invariants = rules that must always be true for this entity to be valid.
     * Enforce them once here so the rest of your code can trust the entity.
     */
    private assertInvariants(): void {
        if (!this.props.documentId) throw new Error("EformsignDocEntity: documentId is required");

        if (!(this.props.createdDate instanceof Date) || Number.isNaN(this.props.createdDate.getTime())) {
            throw new Error("EformsignDocEntity: createdDate must be a valid Date");
        }
        if (!(this.props.updatedDate instanceof Date) || Number.isNaN(this.props.updatedDate.getTime())) {
            throw new Error("EformsignDocEntity: updatedDate must be a valid Date");
        }
        if (this.props.updatedDate < this.props.createdDate) {
            throw new Error("EformsignDocEntity: updatedDate cannot be before createdDate");
        }

        if (!this.props.statusType) throw new Error("EformsignDocEntity: statusType is required");
        if (!this.props.statusDetail) throw new Error("EformsignDocEntity: statusDetail is required");

        if (!this.props.stepType) throw new Error("EformsignDocEntity: stepType is required");
        if (!this.props.stepIndex) throw new Error("EformsignDocEntity: stepIndex is required");
        if (!this.props.stepName) throw new Error("EformsignDocEntity: stepName is required");

        if (!this.props.stepRecipientType) throw new Error("EformsignDocEntity: stepRecipientType is required");
        if (!this.props.stepRecipientName) throw new Error("EformsignDocEntity: stepRecipientName is required");
        if (!this.props.stepRecipientSms) throw new Error("EformsignDocEntity: stepRecipientSms is required");

        if (!(this.props.expiredDate instanceof Date) || Number.isNaN(this.props.expiredDate.getTime())) {
            throw new Error("EformsignDocEntity: expiredDate must be a valid Date");
        }
        if (typeof this.props.expired !== "boolean") {
            throw new Error("EformsignDocEntity: expired must be a boolean");
        }

        if (typeof this.props.clientId !== "number" || this.props.clientId <= 0) {
            throw new Error("EformsignDocEntity: clientId must be a positive number");
        }
    }

    // Accessors (optional, but keeps props encapsulated)
    get id(): number | undefined { return this.props.id; }
    get documentId(): string { return this.props.documentId; }
    get createdDate(): Date { return this.props.createdDate; }
    get updatedDate(): Date { return this.props.updatedDate; }
    get statusType(): string { return this.props.statusType; }
    get statusDetail(): string { return this.props.statusDetail; }
    get stepType(): string { return this.props.stepType; }
    get stepIndex(): string { return this.props.stepIndex; }
    get stepName(): string { return this.props.stepName; }
    get stepRecipientType(): string { return this.props.stepRecipientType; }
    get stepRecipientName(): string { return this.props.stepRecipientName; }
    get stepRecipientSms(): string { return this.props.stepRecipientSms; }
    get expiredDate(): Date { return this.props.expiredDate; }
    get expired(): boolean { return this.props.expired; }
    get clientId(): number { return this.props.clientId; }
    get collectionStartDate(): Date | null { return this.props.collectionStartDate ?? null; }
    get collectionEndDate(): Date | null { return this.props.collectionEndDate ?? null; }
    get collectionPeriodDays(): number | null { return this.props.collectionPeriodDays ?? null; }
    get finalizedAt(): Date | null { return this.props.finalizedAt ?? null; }
    get forceFinalize(): boolean { return this.props.forceFinalize ?? false; }

    /**
     * Use this for "API JSON → select fields → create entity".
     * If you don't have updatedDate yet, it defaults to createdDate.
     * id is auto-generated by DB, so it's omitted here.
     */
    static create(
        props: Omit<EformsignDocProps, "id" | "updatedDate"> & Partial<Pick<EformsignDocProps, "updatedDate">>,
    ): EformsignDocEntity {
        return new EformsignDocEntity({
            ...props,
            updatedDate: props.updatedDate ?? props.createdDate,
        });
    }

    /**
     * Reconstitute an entity from persistence data (used by Mapper).
     * This method is infrastructure-agnostic - it only knows domain types.
     */
    static reconstitute(props: EformsignDocProps): EformsignDocEntity {
        return new EformsignDocEntity(props);
    }
}


