interface EformsignDocProps {
    id?: number; // auto-generated by DB, optional on create
    documentId: string;
    createdDate: Date;
    updatedDate: Date;
    // doc status code example: 060 = pending, 050 = completed, 080 = rejected
    statusType: string;
    // doc status detail example: "대기", "완료", "거부"
    statusDetail: string;
    // step type example: "05" = participant, "06" = reviewer
    stepType: string;
    // step index example: "2"
    stepIndex: string;
    // step name example: "이용자 성명"
    stepName: string;
    // step recipients example: [{ type: "05", name: "이용자 성명", sms: "010-1234-5678" }]
    stepRecipientType: string;
    // step recipient name example: ["이용자 성명"]
    stepRecipientName: string;
    // step recipient sms example: ["010-1234-5678"]
    stepRecipientSms: string;
    // expired date example: 2025-12-13
    expiredDate: Date;
    // expired example: true
    expired: boolean;
    // FK to client
    clientId: number;
}

export class EformsignDocEntity {
    private readonly props: EformsignDocProps;

    constructor(props: EformsignDocProps) {
        this.props = {
            ...props,
        };
        this.assertInvariants();
    }

    /**
     * Invariants = rules that must always be true for this entity to be valid.
     * Enforce them once here so the rest of your code can trust the entity.
     */
    private assertInvariants(): void {
        if (!this.props.documentId) throw new Error("EformsignDocEntity: documentId is required");

        if (!(this.props.createdDate instanceof Date) || Number.isNaN(this.props.createdDate.getTime())) {
            throw new Error("EformsignDocEntity: createdDate must be a valid Date");
        }
        if (!(this.props.updatedDate instanceof Date) || Number.isNaN(this.props.updatedDate.getTime())) {
            throw new Error("EformsignDocEntity: updatedDate must be a valid Date");
        }
        if (this.props.updatedDate < this.props.createdDate) {
            throw new Error("EformsignDocEntity: updatedDate cannot be before createdDate");
        }

        if (!this.props.statusType) throw new Error("EformsignDocEntity: statusType is required");
        if (!this.props.statusDetail) throw new Error("EformsignDocEntity: statusDetail is required");

        if (!this.props.stepType) throw new Error("EformsignDocEntity: stepType is required");
        if (!this.props.stepIndex) throw new Error("EformsignDocEntity: stepIndex is required");
        if (!this.props.stepName) throw new Error("EformsignDocEntity: stepName is required");

        if (!this.props.stepRecipientType) throw new Error("EformsignDocEntity: stepRecipientType is required");
        if (!this.props.stepRecipientName) throw new Error("EformsignDocEntity: stepRecipientName is required");
        if (!this.props.stepRecipientSms) throw new Error("EformsignDocEntity: stepRecipientSms is required");

        if (!(this.props.expiredDate instanceof Date) || Number.isNaN(this.props.expiredDate.getTime())) {
            throw new Error("EformsignDocEntity: expiredDate must be a valid Date");
        }
        if (typeof this.props.expired !== "boolean") {
            throw new Error("EformsignDocEntity: expired must be a boolean");
        }

        if (typeof this.props.clientId !== "number" || this.props.clientId <= 0) {
            throw new Error("EformsignDocEntity: clientId must be a positive number");
        }
    }

    // Accessors (optional, but keeps props encapsulated)
    get id(): number | undefined { return this.props.id; }
    get documentId(): string { return this.props.documentId; }
    get createdDate(): Date { return this.props.createdDate; }
    get updatedDate(): Date { return this.props.updatedDate; }
    get statusType(): string { return this.props.statusType; }
    get statusDetail(): string { return this.props.statusDetail; }
    get stepType(): string { return this.props.stepType; }
    get stepIndex(): string { return this.props.stepIndex; }
    get stepName(): string { return this.props.stepName; }
    get stepRecipientType(): string { return this.props.stepRecipientType; }
    get stepRecipientName(): string { return this.props.stepRecipientName; }
    get stepRecipientSms(): string { return this.props.stepRecipientSms; }
    get expiredDate(): Date { return this.props.expiredDate; }
    get expired(): boolean { return this.props.expired; }
    get clientId(): number { return this.props.clientId; }

    /**
     * Use this for "API JSON → select fields → create entity".
     * If you don't have updatedDate yet, it defaults to createdDate.
     * id is auto-generated by DB, so it's omitted here.
     */
    static create(
        props: Omit<EformsignDocProps, "id" | "updatedDate"> & Partial<Pick<EformsignDocProps, "updatedDate">>,
    ): EformsignDocEntity {
        return new EformsignDocEntity({
            ...props,
            updatedDate: props.updatedDate ?? props.createdDate,
        });
    }

    /**
     * Maps a Prisma row into a domain entity.
     * Field names depend on your Prisma schema (this matches the project's snake_case convention).
     */
    static fromPrisma(prismaData: {
        id: number;
        document_id: string;
        created_date: Date;
        updated_date: Date;
        status_type: string;
        status_detail: string;
        step_type: string;
        step_index: string;
        step_name: string;
        step_recipient_type: string;
        step_recipient_name: string;
        step_recipient_sms: string;
        expired_date: Date;
        expired: boolean;
        client_id: number;
    }): EformsignDocEntity {
        return new EformsignDocEntity({
            id: prismaData.id,
            documentId: prismaData.document_id,
            createdDate: prismaData.created_date,
            updatedDate: prismaData.updated_date,
            statusType: prismaData.status_type,
            statusDetail: prismaData.status_detail,
            stepType: prismaData.step_type,
            stepIndex: prismaData.step_index,
            stepName: prismaData.step_name,
            stepRecipientType: prismaData.step_recipient_type,
            stepRecipientName: prismaData.step_recipient_name,
            stepRecipientSms: prismaData.step_recipient_sms,
            expiredDate: prismaData.expired_date,
            expired: prismaData.expired,
            clientId: prismaData.client_id,
        });
    }

    /**
     * Prepare this entity into a DB-friendly shape (Prisma create/update data).
     */
    toPersistence(): {
        document_id: string;
        created_date: Date;
        updated_date: Date;
        status_type: string;
        status_detail: string;
        step_type: string;
        step_index: string;
        step_name: string;
        step_recipient_type: string;
        step_recipient_name: string;
        step_recipient_sms: string;
        expired_date: Date;
        expired: boolean;
        client_id: number;
    } {
        return {
            document_id: this.props.documentId,
            created_date: this.props.createdDate,
            updated_date: this.props.updatedDate,
            status_type: this.props.statusType,
            status_detail: this.props.statusDetail,
            step_type: this.props.stepType,
            step_index: this.props.stepIndex,
            step_name: this.props.stepName,
            step_recipient_type: this.props.stepRecipientType,
            step_recipient_name: this.props.stepRecipientName,
            step_recipient_sms: this.props.stepRecipientSms,
            expired_date: this.props.expiredDate,
            expired: this.props.expired,
            client_id: this.props.clientId,
        };
    }
}


